experiment_id: 2190310A384BC90EF
application_name: tfb-qrh-sample
trials:
  - app-version: v1
    info:
      trial_id: ''
      trial_num: 15
    settings:
      trail_settings:
        trial_run: 23mins
        trial_measurement_time: 3mins
        trial_iterations: 5
      deployment_settings:
        deployment_policy:
          type: newDeployment
          target_env: qa
          agent: CLI
        deployment_tracking:
          trackers:
            - training
            - production
    deployments:
      - training:
          deployment_name: tfb-qrh-sample
          state: ''
          result: ''
          result_info: ''
          result_error: ''
          metrics:
            - name: request_sum
              query: sum(rate(http_server_requests_seconds_sum{exception=none}[3m])) by (pod)
              datasource: prometheus
            - name: request_count
              query: sum(rate(http_server_requests_seconds_count{exception=none}[3m])) by (pod)
              datasource: prometheus
            - name: cpu_usage
              query: sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (pod)
              datasource: prometheus
            - name: memory_usage
              query: sum(container_memory_working_set_bytes) by (pod)
              datasource: prometheus
          config:
            - name: update requests and limits
              spec:
                template:
                  spec:
                    container:
                      resources:
                        requests:
                          cpu: 2.47
                          memory: 900Mi
                        limits:
                          cpu: 2.47
                          memory: 900Mi
            - name: update env
              spec:
                template:
                  spec:
                    container:
                      env:
                        JAVA_OPTIONS: >-
                          -server -XX:MaxInlineLevel=16
                          -Dquarkus.thread-pool.core-threads=15
                          -Dquarkus.thread-pool.queue-size=748
                          -Dquarkus.datasource.jdbc.min-size=2
                          -Dquarkus.datasource.jdbc.max-size=44
