experiment_id: 2190310A384BC90EF
application_name: tfb-qrh-sample
trials:
  - app-version: v1
    info:
      trial_id: ''
      trial_num: 38
    settings:
      trail_settings:
        trial_run: 6mins
        trial_measurement_time: 3mins
        trial_iterations: 3
      deployment_settings:
        deployment_policy:
          type: newDeployment
          target_env: qa
          agent: CLI
        deployment_tracking:
          trackers:
            - training
            - production
    deployments:
      - training:
          deployment_name: tfb-qrh-sample
          state: ''
          result: ''
          result_info: ''
          result_error: ''
          metrics:
            - name: request_sum
              query: sum(rate(http_server_requests_seconds_sum{exception=none}[3m])) by (pod)
              datasource: prometheus
            - name: request_count
              query: sum(rate(http_server_requests_seconds_count{exception=none}[3m])) by (pod)
              datasource: prometheus
            - name: cpu_usage
              query: sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (pod)
              datasource: prometheus
            - name: memory_usage
              query: sum(container_memory_working_set_bytes) by (pod)
              datasource: prometheus
          config:
            - name: update requests and limits
              spec:
                template:
                  spec:
                    container:
                      resources:
                        requests:
                          cpu: 3.88
                          memory: 3357Mi
                        limits:
                          cpu: 3.88
                          memory: 3357Mi
            - name: update env
              spec:
                template:
                  spec:
                    container:
                      env:
                        JAVA_OPTIONS: i>-
                          -server -XX:+UseG1GC -XX:MaxRAMPercentage=70
                          -Dquarkus.thread-pool.core-threads=7 -Dquarkus.thread-pool.queue-size=6220
                          -Dquarkus.datasource.jdbc.min-size=12 -Dquarkus.datasource.jdbc.initial-size=12 -Dquarkus.datasource.jdbc.max-size=55
                          -XX:FreqInlineSize=345 -XX:MaxInlineLevel=37 -XX:MinInliningThreshold=157 -XX:CompileThreshold=4120 -XX:CompileThresholdScaling=2.2
                          -XX:ConcGCThreads=7 -XX:ParallelGCThreads=7 -XX:InlineSmallCode=4339 -XX:LoopUnrollLimit=228 -XX:LoopUnrollMin=12 -XX:MinSurvivorRatio=13
                          -XX:NewRatio=2 -XX:TieredStopAtLevel=2 -XX:-TieredCompilation -XX:+AllowParallelDefineClass -XX:-AllowVectorizeOnDemand
                          -XX:-AlwaysCompileLoopMethods -XX:-AlwaysPreTouch -XX:+AlwaysTenure -XX:+BackgroundCompilation -XX:+DoEscapeAnalysis -XX:+UseInlineCaches
                          -XX:+UseLoopPredicate -XX:-UseStringDeduplication -XX:-UseSuperWord -XX:-UseTypeSpeculation
